### ISSUE TITLE
Import intel-vaapi-driver package at newer version to fix vaapi

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixpkgs-wayland#107]
see the upstream issue for more details: https://github.com/NixOS/nixpkgs/issues/55975

pros:
* This should fix vaapi which is probably broken for nixos-unstable + intel + wayland users, if I understand the issues at play correctly

con:
* pushing more unstable software into this overlay which users might not expect

**Comment by yorickvP** [comment]
Would it be possible to push that upstream?

**Comment by colemickens** [comment]
@yorickvP Can you elaborate? I have:
1. The upstream issue in nixpkgs already: https://github.com/NixOS/nixpkgs/issues/55975. Feel free to +1, but I'm not likely to push for it since `intel-vaapi-driver` doesn't have a new stable release yet.
2. I've asked for a new release of `intel-vaapi-driver` somewhere in the intel repo already. I didn't get a reply and it looks like they only have a couple releases a year.

So I'm not sure what else I can do. Let me know what you think.

**Comment by yorickvP** [comment]
Personally I would attempt bumping the nixpkgs version to git, or backport
the relevant fix with a fetchPatch. VA support on wayland seems pretty
important.

Op vr 15 mrt. 2019 om 00:55 schreef Cole Mickens <notifications@github.com>:

**Comment by colemickens** [comment]
Okay. Feel free to +1 this: https://github.com/NixOS/nixpkgs/issues/55975 I'll bring it up in IRC as well.

**Comment by colemickens** [comment]
See also: https://github.com/intel/intel-vaapi-driver/issues/449

**Comment by colemickens** [comment]
This was basically fixed by upstream merging my PR.
