### ISSUE TITLE
sway compiling master as 1.0

### ISSUE THREAD

**Issue by yorickvP** [colemickens/nixpkgs-wayland#137]
current sway is `cdcc2a5bb52a34865eee2ec3d09a38b047c08ffd`, but it has the version string `1.0`. This seems wrong.

**Comment by colemickens** [comment]
They removed the option to specify the version as a meson flag and I've
stubbornly chosen to not patch their meson build file in the Nix derivation.

Patches welcomed.

**Comment by cryptix** [comment]
hey @colemickens! can you maybe explain a little more about what this means for some1 not familiar with meson and how it might relate to 1.1-rc1?

**Comment by colemickens** [comment]
@cryptix There's no impact, other than `sway --version` outputting the wrong thing.

I'll try to fix this today, so the reported version is accurate, as well as push a huge number of changes and updates that I've been sitting on.

**Comment by colemickens** [comment]
This is fixed now:

```
[cole@xeep:~]$ sway --version
sway version 00cffb8e20d4bb800134f26dcda8a01afa4467d2

[cole@xeep:~]$ swaymsg -t get_version
sway version 00cffb8e20d4bb800134f26dcda8a01afa4467d2

[cole@xeep:~]$ swaybg --version
swaybg version 25c6eaf15e64655385f01cbb98bffe28a862fe13

[cole@xeep:~]$ swaylock --version
swaylock version a9b274eb6c63397273515151324add022a3db2a9
```
