### ISSUE TITLE
Redshift-wayland no longer works

### ISSUE THREAD

**Issue by Spass1966** [colemickens/nixpkgs-wayland#139]
As of about a week ago. 

Previously, redshift would report it had detected a wayland session and then kick into gear, now no mention of wayland is made and the program simply stalls.

Logs:
```
redshift -l 26.82:30.80 -vvvv
Solar elevations: day above 3.0, night below -6.0
Temperatures: 6500K at day, 4500K at night
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method `randr'.
Waiting for initial location to become available...
Location: 26.82 N, 30.80 E
Color temperature: 6500K
Brightness: 1.00
Status: Enabled
Period: Night
Color temperature: 4500K
```

**Comment by colemickens** [comment]
There's a CLI arg to override the method used. Can you force it to use Wayland? It's a bit weird, I haven't touched anything in this repo for a couple weeks, and as far as I know it's working on my machine. I'll take a look later, but I'm curious if it works when you force the `wayland` method.

**Comment by Spass1966** [comment]
```
~> redshift -m list
Available adjustment methods:
  drm
  randr
  vidmode
  dummy

Specify colon-separated options with `-m METHOD:OPTIONS'.
Try `-m METHOD:help' for help.
~> redshift -l 26.82:30.80 -m wayland -vvvv
Unknown adjustment method `wayland'.
```

**Comment by Spass1966** [comment]
Just updated and wayland is still missing as an available method

**Comment by colemickens** [comment]
Something else must be wrong. I'm using this daily.

**Comment by Spass1966** [comment]
You're correct. I had the service definition defined further below, which was pulling in the mainline redshift.
