### ISSUE TITLE
swaybg as standalone package?

### ISSUE THREAD

**Issue by alexarice** [colemickens/nixpkgs-wayland#141]
With the most recent update to sway my background no longer displays.
According to this https://github.com/swaywm/sway/issues/3861#issuecomment-487073065 swaybg has/will be made a standalone project which sway depends on. I wonder if this is the cause. I have checked that the nixpkgs sway has swaybg in it but the one from here seems to not have it.
Would be nice to know if anyone else has the same problem

**Comment by colemickens** [comment]
Oh thanks, I'd noticed it but not looked into it. I'll try to fix this asap. In the meantime you might be able to use the swaybg from nixpkgs?

**Comment by alexarice** [comment]
It's not urgent as everything else still works, I could take a look at packaging this later today if that would be helpful
