### ISSUE TITLE
Black screen for Sway

### ISSUE THREAD

**Issue by alexherbo2** [colemickens/nixpkgs-wayland#214]
I have a black screen since the last update.

https://gist.github.com/e3ce5f4947455a95f3a2f73a1d40fb1a

**Comment by colemickens** [comment]
I've been hitting the same thing (although for some reason when I tried 20 minutes ago it worked and now I'm in a sway session...).

I was told `wlroots` is broken and I get the impression there's some refactoring going on that might contribute to instability.

Folks can always pin to a version of this repo from a few days ago, for a while, until this passes.

**Comment by alexherbo2** [comment]
How to pin a version?

**Comment by colemickens** [comment]
Example usage:

```nix
{ config, lib, pkgs, ... }:
let
  url = "https://github.com/colemickens/nixpkgs-wayland/archive/master.tar.gz";
  waylandOverlay = (import (builtins.fetchTarball url));
in
  {
    nixpkgs.overlays = [ waylandOverlay ];
    # ...
  }
```

so if you want to pin it, just replace `master` with a rev from this repo.

So if you wanted to pin from a few days ago, say commit: c355b2cc97df57c7ba3abeeb6b703c76946f51d0 (note, I don't know if that's a good revision to use), then you would do:

```nix
{ config, lib, pkgs, ... }:
let
  rev = "c355b2cc97df57c7ba3abeeb6b703c76946f51d0";
  url = "https://github.com/colemickens/nixpkgs-wayland/archive/${rev}.tar.gz";
  waylandOverlay = (import (builtins.fetchTarball url));
in
  {
    nixpkgs.overlays = [ waylandOverlay ];
    # ...
  }
```

**Comment by colemickens** [comment]
Note, I'm not reverting this because `wlroots` has been relatively unstable lately anyway, and I'd rather let it get fixed than try to find a good version and keep it pinned.

Also, if you do this, make sure you leave a reminder to undo it!

**Comment by alexherbo2** [comment]
It could be nice to have this in the wiki you linked in the README – in addition to the example usage.

https://nixos.wiki/wiki/Overlays

**Comment by alexherbo2** [comment]
It appears to work again.
