### ISSUE TITLE
package request: emacs-pgtk-native-comp

### ISSUE THREAD

**Issue by bnjmnt4n** [colemickens/nixpkgs-wayland#237]
The native-comp branch of Emacs provides a great performance boost, and using a pure Wayland compatible version of Emacs would prevent fuzzy scaling on my HiPDI device. Such a fork exists here: https://github.com/fejfighter/emacs/tree/pgtk-nativecomp. Note: I believe building the native-comp branch could potentially take a long time, so I haven't done it myself yet.

**Comment by colemickens** [comment]
How does this compare to the `emacs-pgtk` that @bqv contributed? Is it indeed different? https://github.com/colemickens/nixpkgs-wayland/blob/master/pkgs/emacs/default.nix#L12

**Comment by bqv** [comment]
I actually use this now, too. It's just a dirty merge of the two feature branches so you don't have to pick one.

**Comment by bnjmnt4n** [comment]
Actually, after a while I found another overlay that does package this up: https://github.com/mjlbach/emacs-pgtk-nativecomp-overlay. I couldn't seem to download binaries from Cachix, so I had to compile manually, which was actually much faster than expected (I read that it used to take hours). In summary: there already exists an overlay with Emacs pgtk and native-comp, so I guess it's up to the maintainer to decide on whether such a package should be added to this repo, or just defer to the other overlay.

**Comment by berbiche** [comment]
The "overlay" part won't be imposed anymore once my PR is complete and merged <https://github.com/mjlbach/emacs-pgtk-nativecomp-overlay/pull/24>.

@colemickens What is your policy on wrapping external nix packages?

**Comment by bqv** [comment]
Is there any real point? It already has a cache

**Comment by berbiche** [comment]
I was thinking in terms of centralizing packages. Discovery is not easy for newcomers to Nix.

**Comment by mjlbach** [comment]
FWIW I'm in favor of emacs-pgtk-nativecomp being added to nixpkgs-wayland since I know I dislike adding multiple cachix cache's to my setup, so the more consolidation the merrier! I see #239 does this.

**Comment by bnjmnt4n** [comment]
@mjlbach thanks for setting up the overlay! The cachix issues are probably due to some misconfiguration on my part, but for now I'm using https://github.com/mjlbach/emacs-pgtk-nativecomp-overlay/pull/24 for flakes compatibility, so I believe the caches aren't set up for that yet.

**Comment by mjlbach** [comment]
Ah, yeah. I never merged that PR, and it doesn't have the right perms to push to my cachix. I'll check in with @berbiche about rebasing and making sure it's working with non-flakes systems as well (at least until nixpkgs-wayland subsumes the overlay)

**Comment by berbiche** [comment]
It's in my to-do list. I'll try to tackle this next Monday.

**Comment by bqv** [comment]
There's now pgtk builds in emacs-overlay, fyi. Might supercede need for any emacs builds in this flake

**Comment by mjlbach** [comment]
To clarify there is a pgtk + nativecomp build for the emacs-overlay, I've deprecated my overlay because of this.

**Comment by bnjmnt4n** [comment]
Cool, thanks for the update! In that case, I guess it's up to @colemickens to decide, although I agree that centralizing all emacs packages to emacs-overlay seems like a good idea.

**Comment by colemickens** [comment]
Yeah, that makes sense to me too. Thanks for the updates folks (I'm not an emacs guy).

I'll close the open PR and remove the existing emacs package soon. I need to dedicate a day or two to maintenance-y stuff.
