### ISSUE TITLE
wf-recorder recording doesn't stop

### ISSUE THREAD

**Issue by Kazimazi** [colemickens/nixpkgs-wayland#242]
To stop recording with wf-recorder you would have to send SIGINT to it (like Ctrl+C from terminal). When I run wf-recorder using this overlay: `nix run "github:colemickens/nixpkgs-wayland#wf-recorder"` it wouldn't stop on SIGINT, rendering it's recording unusable.
Building it from nixpkgs-20.09 works as intended.

**Comment by colemickens** [comment]
This is probably more of an issue with Nix, rather than with `wf-recorder` or this overlay.

I'd search the nixos/nix repo for "SIGINT" and maybe report a new issue if you think its blocking CTRL-C and think it should work differently.

**Comment by Kazimazi** [comment]
works now
