### ISSUE TITLE
waybar is pinned to 0.9.4

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixpkgs-wayland#243]
`waybar` is currently broken against both `nixos-unstable` and `nixos-unstable-small`, even though stable waybar in nixpkgs builds correctly.

**Comment by colemickens** [comment]
`waybar` was temporarily removed from the overlay until it can be fixed (or until it's fixed in nixpkgs and we can benefit from the fix).

**Comment by colemickens** [comment]
waybar was temporarily removed from the overlay until it can be fixed (or until it's fixed in nixpkgs and we can benefit from the fix).

**Comment by colemickens** [comment]
Changed my mind again, I'm going to just leave Waybar pinned at `0.9.4`.

**Comment by berbiche** [comment]
My quick overlay fix:

``` nix
final: prev:
let
  fmt = prev.fmt.overrideAttrs (_: rec {
    version = "7.0.3";
    src = prev.fetchFromGitHub {
      owner = "fmtlib";
      repo = "fmt";
      rev = version;
      hash = "sha256-Ks3UG3V0Pz6qkKYFhy71ZYlZ9CPijO6GBrfMqX5zAp8=";
    };
  });
in
{
  waybar = (prev.waybar.override { inherit fmt; }).overrideAttrs (_: rec {
    version = "faacd76f627f4f7ad3413a44870e089fbdb6539e";
    src = prev.fetchFromGitHub {
      owner = "Alexays";
      repo = "Waybar";
      rev = version;
      hash = "sha256-4DsOp25b5Z3vHw4j5LnQcvVdh+vrM9JpOJdY/JhKawk=";
    };
  });
}
```

**Comment by Artturin** [comment]
if the fmt version was the issue then maybe this fixed it https://github.com/Alexays/Waybar/pull/929

**Comment by colemickens** [comment]
Funny enough, I just tried unpinning waybar about 10 minutes ago and it was still failing.

If you want to try, you can clone this repo, `nix-shell shell.nix`, remove `skip:true` from `pkgs/waybar/metadata.nix` then run `./update.sh`.

**Comment by Artturin** [comment]
Maybe someone will fix waybar now :P 
https://github.com/Alexays/Waybar/releases/tag/0.9.5

**Comment by Artturin** [comment]
@colemickens waybar builds now

**Comment by colemickens** [comment]
waybar was unpinned in commit: https://github.com/colemickens/nixpkgs-wayland/commit/fd77b9e3a1b62fddc006a550d03cfc3b22f279a1

waybar was then updated: https://github.com/colemickens/nixpkgs-wayland/commit/a1e8717c8ad008779387f41d84d8dec7a2c75259
