### ISSUE TITLE
Investigate updating dependencies automatically using Niv

### ISSUE THREAD

**Issue by berbiche** [colemickens/nixpkgs-wayland#246]
See comment thread starting from https://github.com/colemickens/nixpkgs-wayland/pull/238#issuecomment-735011193 for context.

Niv: https://github.com/nmattia/niv

**Comment by colemickens** [comment]
I'd definitely be more interested if it supported mercurial, or supported a custom command for determining `rev`.

**Comment by colemickens** [comment]
Is there any reason why I wouldn't use flakes for this, actually?

The most difficult part would be re-implementing things like "skip", but that wouldn't be that hard.

**Comment by colemickens** [comment]
Oh right, the problem always comes back to cargo/vendor Sha256.

**Comment by berbiche** [comment]
> Oh right, the problem always comes back to cargo/vendor Sha256.

I don't understand what the issue is, would you care to elaborate? 😄

**Comment by colemickens** [comment]
`niv` doesn't know how to update the `cargoSha256` and `vendorSha256` values that Rust and Go packages need to have updated when they get bumps.

That's what this does, after it updates `rev`/`sha256`: https://github.com/colemickens/nixpkgs-wayland/blob/b9db16d610dc1ce6087cf4070e6394a11d0115fc/update.sh#L91-L105

**Comment by berbiche** [comment]
@colemickens have you heard of https://github.com/Mic92/nix-update ?
It handles updating the cargoSha256 as well.
I've only ever used it to update the Rust tool `bottom`.

**Comment by berbiche** [comment]
Closing this as I don't plan on working on this anytime soon

**Comment by colemickens** [comment]
BTW, I don't know if you saw but I wound up sort of rewriting `update.sh`. It's a bit simpler, doesn't use any external tool (or extra nixpkgs downloads for it), and is used being used 1:1 in other projects to update packages that are laid out the way I have (with `metadata.nix`), but even that could be relaxed to find/replace in the entire pkg dir.

All-in-all, I'd still rather out-source this to an external tool. **mic92** makes great stuff so I assume sometime `nix-update` will probably just do what I need.
