### ISSUE TITLE
update problem?

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixpkgs-wayland#255]
see https://github.com/colemickens/nixpkgs-wayland/commit/2f8903b63e7a334d750f85270458fbb1e7e041e0#r45400340

cc: @Emantor

**Comment by colemickens** [comment]
This is odd... (from the CI where this commit happened: https://azusa.runners.sr.ht/logs/374982/update/log (see attached)
[job.log](https://github.com/colemickens/nixpkgs-wayland/files/5739808/job.log)


```
pkgs/wlroots/: checking
pkgs/wlroots/: 55b02f753f6bdc004ac2f7af27f89d82946b8701 => f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07
+ [[ pkgs == \p\k\g\s ]]
++ NIX_PATH=nixpkgs=https://api.github.com/repos/nixos/nixpkgs/tarball/e9158eca70ae59e73fae23be5d13d3fa0cfc78b4
++ nix-prefetch --output raw -E '{rev, sha256}: (import ./packages.nix).wlroots.src.overrideAttrs(old:{rev=rev;sha256=sha256;})' --rev f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07

�[K
�[KThe fetcher will be called as follows:
> <unnamed> {
>   rev = "f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07";
>   sha256 = "0000000000000000000000000000000000000000000000000000";
> }

+ newsha256=1sc5dwxafa7jzydrjy39c7bpxhbqx7rr1yq7mckxb4w4998jafhs
+ sed -i s/55b02f753f6bdc004ac2f7af27f89d82946b8701/f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07/ pkgs/wlroots//metadata.nix
+ sed -i 's|1sc5dwxafa7jzydrjy39c7bpxhbqx7rr1yq7mckxb4w4998jafhs|1sc5dwxafa7jzydrjy39c7bpxhbqx7rr1yq7mckxb4w4998jafhs|' pkgs/wlroots//metadata.nix
+ [[ missing_cargoSha256 != \m\i\s\s\i\n\g\_\c\a\r\g\o\S\h\a\2\5\6 ]]
+ [[ missing_vendorSha256 != \m\i\s\s\i\n\g\_\v\e\n\d\o\r\S\h\a\2\5\6 ]]
+ set +x
�[33;1mwarning:�[0m Git tree '/home/build/nixpkgs-wayland' is dirty
�[33;1mwarning:�[0m Git tree '/home/build/nixpkgs-wayland' is dirty
```

Versus... (now, on my machine)
```
❯ nix-prefetch --output raw -E '{rev, sha256}: (import ./packages.nix).wlroots.src.overrideAttrs(old:{rev=rev;sha256=sha256;})' --rev f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07

warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
The fetcher will be called as follows:
> <unnamed> {
>   rev = "f6fc4c28830dd2391d7e61f7cec0c4d2d89d1f07";
>   sha256 = "0000000000000000000000000000000000000000000000000000";
> }

sha256-kKjHafWhqEhWt7vw1p47w+Gd5+mlsYokmKhSv82nj2Y=

❯ nix to-base32 sha256-kKjHafWhqEhWt7vw1p47w+Gd5+mlsYokmKhSv82nj2Y=           
0rlglz6vylm8k0j8mcd5x7krvqf37fgddw5vnxb4ia51ymlwga4h
```

which is presumably the right `sha256`...

I'm a bit confused. Either a very weird `nix-prefetch` bug, or some sort of oddity in GH I don't understand, or a really awful GitHub bug.

**Comment by colemickens** [comment]
Note, this commit changed the update script:
https://github.com/colemickens/nixpkgs-wayland/commit/e094a4d97722be96f86d98bec9a6f2224a7aa4ee

But this should have fixed it, not introduced a problem that only appears some of the time?

**Comment by colemickens** [comment]
Also, normally this might've gone unnoticed, but the current `systemd` issue in nixos-unstable has my cronjob/build job ... apparently down.

**Comment by Emantor** [comment]
> Also, normally this might've gone unnoticed, but the current `systemd` issue in nixos-unstable has my cronjob/build job ... apparently down.

Yes, apparently systemd-resolved is broken. `gethostbyname`libc no longer resolves anything… leading to host working but ping/firefox/… being broken.

**Comment by colemickens** [comment]
This was fixed.
