### ISSUE TITLE
obs-studio: obs doesn't detect plugins.

### ISSUE THREAD

**Issue by lemniskett** [colemickens/nixpkgs-wayland#265]
I installed ```obs-studio-dmabuf``` and ```obs-wlrobs```, but obs doesn't seem to detect the wlrobs plugin in ```${pkgs.obs-wlrobs}/share/obs/obs-plugins```, when i manually copy ```${pkgs.obs-wlrobs}/share/obs/obs-plugins/wlrobs``` to ```~/.config/obs-studio/plugins```, it worked.

**Comment by colemickens** [comment]
That's just how OBS plugins are installed. As the README indicates, I
recommend using home-manager to manage their installation and symlinking.

**Comment by lemniskett** [comment]
Ah, so it's intended, thanks!
