### ISSUE TITLE
obs-xdg-portal: pinned for now

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixpkgs-wayland#275]
https://github.com/colemickens/nixpkgs-wayland/commit/dfe0f92d70fbf54cbf633ae0ed8a6729c29176d7

pinned until `nixos-unstable` gets the newer pipewire.

**Comment by kamushadenes** [comment]
Pipewire in nixos-unstable seems to be `0.3.18` now, what needs to be done for this to work?

I'm getting ```meson.build:13:0: ERROR: Invalid version of dependency, need 'libpipewire-0.3' ['>= 0.3.17'] found '0.3.7'.```

**Comment by colemickens** [comment]
If you're getting that, then you have something wrong. When I pin a package, it's so that "all pacakges" can be updated and built, but skipping certain packages so they stay on working revisions.

It sounds like you probably weren't getting your channel updated...

**Comment by colemickens** [comment]
However, I will also revisit this and unpin `obs-xdg-portal`, but I've got a bigger problem right now: https://github.com/colemickens/nixpkgs-wayland/issues/276

**Comment by kamushadenes** [comment]
I'm at 20.09, so my pipewire is from unstable. I solved with overrideAttrs:

```
    (obs-xdg-portal.overrideattrs (old: {
      buildinputs =
        [ obs-studio-dmabuf gtk3 unstable.pipewire xdg-desktop-portal ];
    }))
```

**Comment by colemickens** [comment]
Another option is pulling the entire `obs-xdg-portal` package from this repo as a package set, rather than as an overlay. You'd get more cache hits that way too. But I don't know that it's better than what you did.

**Comment by colemickens** [comment]
fixed in:
* https://github.com/colemickens/nixpkgs-wayland/commit/69a189c7f81977932ef55077b89143bfcb3b644a
* https://github.com/colemickens/nixpkgs-wayland/commit/a82684e02606e6bfffd5685cc8ce12079c45e181
