### ISSUE TITLE
xorg-xserver 1.20

### ISSUE THREAD

**Issue by zimbatm** [colemickens/nixpkgs-wayland#30]
nixpkgs-unstable is currently stuck on an older version. xwayland is part of the xorg-xserver distribution

the new version brings things like better multi-cursor support so we probably want to have it upgraded.

see https://github.com/NixOS/nixpkgs/issues/44492

**Comment by lovesegfault** [comment]
This can be closed (upstream has picked up a new xorg-xserver)
