### ISSUE TITLE
documentation: provide working config

### ISSUE THREAD

**Issue by gilligan** [colemickens/nixpkgs-wayland#33]
It would be great if you could provide a small working configuration that shows how to get things up and running with wayland and sway.

**Comment by colemickens** [comment]
@gilligan Can you elaborate a bit? Is there more you'd like to see than maybe a link to a default Sway config?

The upstream default config for Sway is available here: https://github.com/swaywm/sway/blob/master/config.in

**Comment by gilligan** [comment]
Maybe i am being slightly silly here in that case sorry, but I don’t actually know exactly how I would go about switching from my current i3 setup to using wayland..

I have a fairly standard xserver section with slim enabled and windowManager.default set to i3.

Maybe what I am asking is some sort of “how to migrate” info section. Does that make more sense now?

**Comment by colemickens** [comment]
@gilligan Hey, were you able to get things working?
