### ISSUE TITLE
Not able to SSH after a while

### ISSUE THREAD

**Issue by zimbatm** [colemickens/nixpkgs-wayland#49]
I am currently using GnuPG as the SSH agent in NixOS. After a while, SSH connections get stuck during the key negotiation phase.

I suspect that GnuPG tries to spawn the pinentry dialog and is not able to do so for some reason.

This report is missing a lot of details but wanted to have it there as a placeholder. I will put more information as they come.

**Comment by colemickens** [comment]
If this is still an issue, feel free to open a new issue.
